# Generated by Django 3.1.2 on 2020-11-01 15:00

from django.db import migrations
import json


def load_data(apps, schema_editor):

    employee = apps.get_model('empapp', 'Employee')
    db_alias = schema_editor.connection.alias

    with open('empapp/migrations/EmployeeData.json', 'r') as fp:
        data = json.load(fp)

    employee_data = [employee(employee_id=employee_Map['Employee ID'], city_name=employee_Map['City Name'],
                              salary=employee_Map['Salary'], first_name=employee_Map['First Name'],
                              second_name=employee_Map['Second Name'], manager_emp_id=employee_Map['Manager Emp Id'])
                     for employee_Map in data]

    employee.objects.using(db_alias).bulk_create(employee_data)


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
